### ISSUE TITLE
[DESIGN] Creación de diseño para landing page

### ISSUE THREAD

**Issue by JMJHOX** [BOOTCAMP-PTY/BCPTY-FRONTEND#4]
Se necesitaría un diseño base para lo que sería la creación de la landing page, y establecer un estándar de diseño dentro de la aplicación.

**Comment by Alek07** [comment]
El diseño inicial se encuentra en el figma y ya se esta trabajando en él

https://www.figma.com/file/ZjWBL3R2xaNT5pM7lbnKdW/MVP-BOOTCAMPTY?node-id=13%3A2
